# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
    terraform {
      required_providers {
        google = {
          source  = "hashicorp/google"
          version = "5.19.0"
        }
      }
      
        required_version = ">= 1.6"
    }

    provider "google" {
      project = var.project_id
      region  = var.region
    }

